server:
  port: 8080
  servlet:
    context-path: /weatherservice

spring:
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:testdb
    username: SA
  h2:
    console:
      enabled: true

